---
title: "Project"
author: "Teshale"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
library(tidyverse) 
#game_data <- read_csv("BGGdata.csv", show_col_types = FALSE) 
game_data <- read_csv("bgg_db_2017_04.csv/bgg_db_2017_04.csv")
board_game <- read.csv("board_game_popularity_over_years.csv") 
#artists_reduced <- read.csv("artists_reduced.csv/artists_reduced.csv") 
glimpse(game_data) 
glimpse(board_game) 
#glimpse(artists_reduced)

```
# the populartiy of the game over a year
```{r}
board_game %>% ggplot(aes(x = yearpublished, y = count)) + geom_line()
```
# How many games are in the dataset?
```{r}
# Count the number of rows (games) in the dataset
num_games <- nrow(game_data)
print(paste("Number of games:", num_games))

```
```{r}




```

# Calculate the average minimum and maximum number of players
```{r}
average_minplayers <- mean(game_data$minplayers, na.rm = TRUE)
average_maxplayers <- mean(game_data$maxplayers, na.rm = TRUE)
print(paste("Average minimum number of players:", average_minplayers))
print(paste("Average maximum number of players:", average_maxplayers))

```
# highest-rated board games

```{r}

top_rated_games <- game_data %>%
  arrange(desc(avg_rating)) %>%
  select(names, avg_rating) %>%
  head(10)

top_rated_games

```

```{r}
# Plot game ratings by player count
ggplot(game_data, aes(x = min_players, y = avg_rating)) +
  geom_boxplot() +
  labs(title = "Game Ratings by Player Count", x = "Minimum Players", y = "Average Rating")


```
# # Scatter plot of player count vs. ratings
```{r}

ggplot(game_data, aes(x = min_players, y = avg_rating)) +
  geom_point() +
  geom_smooth(method = "lm", col = "red") +
  labs(title = "Player Count vs. Ratings", x = "Minimum Players", y = "Average Rating")

```
```{r}
# Find the highest-rated board games
top_rated_games <- game_data %>%
  arrange(desc(avg_rating)) %>%
  select(names, avg_rating) %>%
  head(10)

print(top_rated_games)

```
```{r}

# Plot the number of games published over time
ggplot(board_game, aes(x = yearpublished, y = count)) +
  geom_line(color = "blue") +
  labs(title = "Number of Games Published Over Time", x = "Year", y = "Number of Games")

```

